CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(50) UNIQUE NOT NULL,
	hashed_password VARCHAR(60) NOT NULL
);

CREATE TABLE likes (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
	kanji_id INTEGER NOT NULL
);